name: build_buck2_nativelink
inputs:
  NATIVELINK_HEADER_RW_KEY_SECRET:
    description: ''
    required: true
runs:
  using: composite
  steps:
  - name: Build `buck2` with `buck2` using remote execution
    run: |-
      {
      echo "[buck2_re_client]
      engine_address       = grpc://scheduler-buck2.build-faster.nativelink.net:443
      action_cache_address = grpc://cas-buck2.build-faster.nativelink.net:443
      cas_address          = grpc://cas-buck2.build-faster.nativelink.net:443
      http_headers         = x-nativelink-api-key:${NATIVELINK_HEADER_RW_KEY}
      tls = true
      instance_name = main
      enabled = true
      capabilities = true
      [build]
        execution_platforms = prelude//platforms:default"
      } > .buckconfig.local
      $RUNNER_TEMP/artifacts/buck2 build //:buck2 -v 4
    env:
      NATIVELINK_HEADER_RW_KEY: ${{ inputs.NATIVELINK_HEADER_RW_KEY_SECRET }}
    shell: bash
